### ISSUE TITLE
Rename student 

### ISSUE THREAD

**Issue by avandam** [timohermans/StudentProgress#21]

**Comment by timohermans** [comment]
Oeh ik besef me dat deze een addertje onder het gras heeft zitten.

Als je een student wilt renamen naar een "oude" student, ga je natuurlijk conflicten krijgen.

Mooie oplossing: alle groups en progresses migreren naar de "nieuwe" bestaande gebruiker.

Minder mooie oplossing: error gooien dat de student al bestaat.

~~Ik ga voor de mooie~~

Bij nader inzien ga ik voor de exception. Conflicts met bijvoorbeeld 'Notes' is me teveel breinbrekerij

**Comment by timohermans** [comment]
Done. Er is een pennetje gekomen naast de student names als je eroverheen hovert (/StudentGroups/Details/Index)
