### ISSUE TITLE
Make milestones in group overview collapsable. 

### ISSUE THREAD

**Issue by avandam** [timohermans/StudentProgress#35]
Usually in a given semester I immediately go to the students, so making the milestones collapsable might be nicer.

Alternatively: changign the order that students are shown first might work as well.

**Comment by timohermans** [comment]
Another alternative is putting the milestones of a group on a separate page. I'll look into it

**Comment by timohermans** [comment]
Decided the easiest solution is moving the milestones table down for now.

Collapsing the table would also require thinking about stuff like default collapse/expand state
